### ISSUE TITLE
Автообновления

### ISSUE THREAD

**Issue by jonkofee** [MirrorsPhoto/electron#17]
Переделать обновление

Сделать модальное окно, в котором будет полный список изменений

**Comment by jonkofee** [comment]
Смотри как это работает

1. При запуске приложения или вручную по нажатию кнопки происходит проверка обновления
2. Если доступна новая версия - во vue отправляется событие `au-update-available` куда отправляется объект вида:

    ```javascript
    {
      version: '2.5.0' //Последняя версия (до которой обновится приложение)
      releaseName: '2.5.0' //Название релиза (совпадает с версией, но не обязательно)
      releaseNotes: [ //Массив с объектами релизов (отсортирован)
        {
          version: '2.5.0',
          note: '<p>Описание релиза 2.5.0</p>' //HTML код описания
        },
        {
          version: '2.4.0',
          note: '<p>Описание релиза 2.4.0</p>'
        },
        ...
      ]
    }
    ```
    Подписаться на него можно так:
    ```javascript
    this.$electron.ipcRenderer.on('au-update-available', (event, data) => {})
    ```
3. Если пользователь соглашается на обновление - его нужно его запустить, делается это так:
    ```javascript
    this.$electron.ipcRenderer.send('au-download-confirm')
    ```
4. Происходит загрузка обновления
5. По окончании загрузки приложение закрывается и запускается уже с новой версией

Так же, если в процессе обновления происходит ошибка - возбуждается событие `au-error`

**Comment by web-crab** [comment]
Или по нажатию на какую кнопку?

**Comment by jonkofee** [comment]
<img width="336" alt="screen shot 2017-10-19 at 22 48 04" src="https://user-images.githubusercontent.com/9060043/31790883-980af9e6-b51f-11e7-8661-cf4d9cb1f9e8.png">
