### ISSUE TITLE
Процесс загрузки обновления

### ISSUE THREAD

**Issue by jonkofee** [MirrorsPhoto/electron#3]
Необходимо реализовать процесс бар загрузки обновления.

При загрузке обновления срабатывает событие `download-progress` на которое я уже подписался и перенаправляю это в vue на событие `au-download-progress`
```javascript
autoUpdater.on('download-progress', (progress) => {
    mainWindow.webContents.send('au-download-progress', progress)
})
```

Тебе необходимо подписаться на него следующим образом
```javascript
this.$electron.ipcRenderer.on('au-download-progress', (data) => { 
    console.log(data.percent) 
}) 
```
У объекта data такая структура
```javascript
var data = {
    bytesPerSecond, // Скорость загрузки
    percent, // Проценты
    total, // Общий размер обновления
    transferred, // Сколько скачано
}
```
Событие `au-download-progress` будет вызвано каждый раз, как поменяется количество скачанных пакетов

По поводу дизайна этого бара нужно еще поговорить. Я себе представляю, что это будет отдельный компонент, вставленный перед `<router-view></router-view>`

```html
<template>
  <update-process-bar></update-process-bar>
  <router-view></router-view>
</template>
```

По теме - пиши ниже

**Comment by web-crab** [comment]
Ты во вью засунул электрон?)

**Comment by jonkofee** [comment]
@klimash Ага
