### ISSUE TITLE
Валидация поля с кодом

### ISSUE THREAD

**Issue by jonkofee** [MirrorsPhoto/electron#30]
Пустой код отправляется на сервер
<img width="392" alt="screen shot 2017-10-19 at 14 24 07" src="https://user-images.githubusercontent.com/9060043/31768710-40813c12-b4d9-11e7-947e-d7282774f054.png">
Проходят символы
<img width="394" alt="screen shot 2017-10-19 at 14 24 00" src="https://user-images.githubusercontent.com/9060043/31768711-40a07366-b4d9-11e7-936b-6ca417115ccf.png">

**Comment by web-crab** [comment]
какая минимальная длина кода?

**Comment by jonkofee** [comment]
13 не больше, не меньше
