### ISSUE TITLE
Стилизовать список обновлений

### ISSUE THREAD

**Issue by jonkofee** [MirrorsPhoto/electron#38]
Навести красоту
<img width="391" alt="screen shot 2017-10-25 at 11 16 27" src="https://user-images.githubusercontent.com/9060043/32005054-faa1f11e-b9ab-11e7-9f41-c0c7492bcdd5.png">

**Comment by web-crab** [comment]
это старый скрин? а то вложенные списки должны быть с черточками

**Comment by jonkofee** [comment]
@klimash старый
