### ISSUE TITLE
Оживить часы

### ISSUE THREAD

**Issue by jonkofee** [MirrorsPhoto/electron#4]
Сделать часы "живыми", чтобы время обновлялось и разделитель мигал

![untitled 2](https://user-images.githubusercontent.com/9060043/30630272-86807384-9de8-11e7-90fe-0cd0b5feba0c.gif)

**Comment by web-crab** [comment]
Я просто не закончил их

**Comment by jonkofee** [comment]
Ну как закончишь - закрой ишус

**Comment by web-crab** [comment]
курсор мигает, время обновляется каждую минуту
