### ISSUE TITLE
Данные о пользователе

### ISSUE THREAD

**Issue by jonkofee** [MirrorsPhoto/electron#5]
При получении токена его нужно расшифровать и куда-то записать.
Есть пакет [jwt-decode](https://www.npmjs.com/package/jwt-decode) для расшифровки.
Хранить его можно в localStorage. нашел интересный [пакет](https://github.com/shidianxia/vue-localforage) для этого, в нём можно легко переключаться между localStorage и WebSQL. По-идее в нём можно хранить объекты, что localStorage не позволяет.

После расшифровки должен получится вот такой объект

<img width="461" alt="screen shot 2017-09-20 at 10 57 24" src="https://user-images.githubusercontent.com/9060043/30632944-834b8924-9df2-11e7-841d-cf1236c22af1.png">

**Comment by jonkofee** [comment]
Протестировал `localforage` - крутая штука, можно объекты хранить. По умолчанию использует IndexedDB, пусть так и будет

**Comment by web-crab** [comment]
сделал запись данных в хранилище и расшифровку
